.PHONY: all
all:
	pdflatex -interaction nonstopmode -haltonerror main.tex
	# -xdotool search --classname mupdf key r

.PHONY: clean
clean:
	rm *.aux *.toc *.snm *.nav *.out *.log *.fdb_latexmk *.fls *.vrb
